[package]
name = "ip_sniffer"
version = "0.2.0"
authors = ["samuel shen"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bpaf = {version = "0.9.6", features = ["derive", "bright-color"]}